### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by mradzinski** [ooJerryLeeoo/hyper-material-box#4]
```
materialBox: {
  scheme: 'material',
}
```
When placed inside module.exports/config throws: 
`An error occurred loading your configuration (/Users/matias/.hyper.js): Unexpected identifier`

**Comment by jerrykal** [comment]
@mradzinski Can you show me your `.hyper.js` ?

**Comment by dpo** [comment]
@mradzinski Perhaps you forgot to add a comma after the previous entry? In my case, I have
```
    copyOnSelect: false,   // <----- COMMA

    // if true, on right click selected text will be copied or pasted if no
    // selection is present (true by default on Windows)
    // quickEdit: true

    // URL to custom bell
    // bellSoundURL: 'http://example.com/bell.mp3',

    // for advanced config flags please refer to https://hyper.is/#cfg
    materialBox: {
      scheme: 'solarized-dark',
      //scheme: 'solarized-light',
    }
  },
```

**Comment by mradzinski** [comment]
It was actually being caused by a combination of my setup and a VERY weird Electron state. For some reason Hyper was reporting hyper-material-box as the one to blame for the error, but it was caused by another plugin (weird AF). No need to keep this open since it's working now and couldn't keep replicating the issue.
