### ISSUE TITLE
ERROR: Cannot read property 'blue' of undefined

### ISSUE THREAD

**Issue by stoe** [ooJerryLeeoo/hyper-material-box#5]
After installing and reopening/reloading Hyper I get the following error popup.

![screenshot 2017-08-03 at 17 23 07](https://user-images.githubusercontent.com/203805/28929542-79961c34-7870-11e7-8bea-725024edb76f.png)

My config is as follows:

```js
module.exports = {
  config: {
    materialBox: {
      scheme: 'material',
      selectedTabFlavor: 'preline',
    }
  },
  plugins: [
    'hyper-material-box'
  ],
  localPlugins: []
};
```

**Comment by jerrykal** [comment]
@stoe Add `colors: {},` in the config section.

``` javascript
module.exports = {
  config: {
    colors: {},
    materialBox: {
      scheme: 'material',
      selectedTabFlavor: 'preline',
    }
  },
  plugins: [
    'hyper-material-box'
  ],
  localPlugins: []
};
```

If the problem not solved yet, feel free to reopen it.
