### ISSUE TITLE
Post Hyper 2.0 upgrade foreground color doesn't appear to be honored on windows 10.

### ISSUE THREAD

**Issue by sloanster4000** [ooJerryLeeoo/hyper-material-box#9]
Foreground set to bold white but it displays as a grey.  
  materialBox: {
            highlightSelectedTab: true,
            user: {
                accentColor: '#ff3300',
                backgroundColor: '#000000',
                **foregroundColor: '#ffffff',**
                cursorColor: '#ff3300',
                colors: {
                    black: '#000000',
                    red: '#ff0000',
                    green: '#1f9900',
                    yellow: '#e6e600',
                    blue: '#0066ff',
                    magenta: '#cc00ff',
                    cyan: '#00ffff',
                    white: '#f2f2f2',
                    lightBlack: '#666666',
                    lightRed: '#ff8080',
                    lightGreen: '#70ff4d',
                    lightYellow: '#ffff4d',
                    lightBlue: '#4d94ff',
                    lightMagenta: '#e580ff',
                    lightCyan: '#b3ffff',
                    lightWhite: '#ffffff',
                },
            },
        },

When I remove materialbox plugin and settings the foregroundColor of bold white is honored     
        // color of the text
        foregroundColor: '#ffffff',

**Comment by dmytro-ulianov** [comment]
The same thing for macOS Sierra

**Comment by t56k** [comment]
This is similar to #8, right? The devtools logs this on load:

> Warning: "hyper-material-box" plugin uses some deprecated CSS classes (x-screen, x-row, cursor-node).

**Comment by sloanster4000** [comment]
Yea same as #8 validated today in dev tools (new to hyper didn't know that you could do this 😀 ) changed 
{opacity:0.6;} to {opacity:1.0;} solved the problem temporarily.
